CREATE TABLE bills (
    id INT AUTO_INCREMENT PRIMARY KEY,
    creation_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    last_mod_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    month VARCHAR(255) NOT NULL UNIQUE,
    house DECIMAL(10, 2) NULL,
    cable DECIMAL(10, 2) NULL,
    water DECIMAL(10, 2) NULL,
    electricity DECIMAL(10, 2) NULL,
    gas DECIMAL(10, 2) NULL
);
