CREATE TABLE bills (
    id INT AUTO_INCREMENT PRIMARY KEY,
    creation_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    las_mod_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    month VARCHAR(255) NOT NULL,
    house VARCHAR(255) NOT NULL,
    cable DECIMAL(10, 2) NOT NULL,
    water DECIMAL(10, 2) NOT NULL,
    electricity DECIMAL(10, 2) NOT NULL,
    gas DECIMAL(10, 2) NOT NULL
);
