CREATE TABLE fuel (
    id INT AUTO_INCREMENT PRIMARY KEY,
    creation_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    last_mod_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    fill_date DATETIME NOT NULL,
    total DECIMAL(10, 2) NOT NULL,
    fuel_amount DECIMAL(10, 2) NOT NULL,
    odometer INT NULL,
);
