CREATE TABLE shoppingItems (
   id CHAR(36) PRIMARY KEY,
   creation_date DATETIME DEFAULT CURRENT_TIMESTAMP,
   last_mod_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   item_name VARCHAR(255) NOT NULL UNIQUE,
   description TEXT
);
