name: Build Dev Pegaso Android Bundle

on: 
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    name: Build Pegaso
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 22.x

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install

      - name: Build Ionic project
        run: ionic build

      - name: Sync Android project
        run: ionic capacitor sync android

      - name: Clean Gradle cache
        run: ./gradlew clean
        working-directory: ./android/      

      - name: Generate bundle
        working-directory: ./android/
        run: ./gradlew bundleRelease
